# Author:: Steven Danna (<steve@chef.io>)
# Copyright:: Copyright (c) 2015 Chef Software, Inc
# License:: Apache License, Version 2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'chef/version'
class Chef
  class Knife
    class SubcommandLoader
      #
      # Load a subcommand from a pre-computed path
      # for the given command.
      #
      class HashedCommandLoader < Chef::Knife::SubcommandLoader
        KEY = '_autogenerated_command_paths'

        attr_accessor :manifest
        def initialize(chef_config_dir, env, plugin_manifest)
          super(chef_config_dir, env)
          @manifest = plugin_manifest
        end

        def subcommand_files
          manifest[KEY]["plugins_paths"].value.flatten
        end

        def load_command(args)
          paths = manifest[KEY]["plugins_paths"][subcommand_for_args(args)]
          if paths.nil?
            ui.fatal("Cannot find sub command for: #{args.join(' ')}")
            ui.fatal("If you recently installed this command, try running: knife rehash -r")
            exit 10
          elsif paths.empty? || (! paths.is_a? Array)
            ui.fatal("Cached information for this subcommand appears to be improperly formatted.")
            ui.fatal("Try running knife rehash -r or removing #{plugin_manifest_path}")
          else
            paths.each do |sc|
              Kernel.load sc
            end
          end
        end

        def subcommand_for_args(args)
          find_longest_key(manifest[KEY]["plugins_paths"], args, "_")
        end
      end
    end
  end
end
